# Generated by Django 5.2.3 on 2025-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(default=263471264),
            preserve_default=False,
        ),
    ]
