# Generated by Django 5.2.3 on 2025-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='username',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='_first_name',
            field=models.TextField(blank=True, db_column='first_name', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='_last_name',
            field=models.TextField(blank=True, db_column='last_name', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='_phone',
            field=models.TextField(db_column='phone', default=8888),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='_username',
            field=models.TextField(blank=True, db_column='username', null=True),
        ),
    ]
