# Generated by Django 5.2.3 on 2025-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='_first_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='_last_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='_username',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
