# Generated by Django 5.2.3 on 2025-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_telegramuser__first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('len', models.IntegerField()),
            ],
        ),
    ]
