# Generated by Django 5.2.3 on 2025-07-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lastuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUser',
        ),
    ]
