# Generated by Django 5.2.3 on 2025-10-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_lastuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
    ]
